/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Dao.DAOFactory;
import Modele.modele.Client;
import java.util.StringTokenizer;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.CaretEvent;

/**
 *
 * @author YOUMBI
 */
public class CreateClients extends javax.swing.JFrame {
     private boolean test = false;
     public static boolean teste;

    /**
     * Creates new form CreateClients
     */
    public CreateClients() {
        initComponents();
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clt2 = new javax.swing.JTextField();
        clt4 = new javax.swing.JTextField();
        clt3 = new javax.swing.JTextField();
        clt6 = new javax.swing.JTextField();
        clt5 = new javax.swing.JTextField();
        clb2 = new javax.swing.JButton();
        clb1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Formulaire d'ajout d'un client");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nom du client");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prenom du client");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Adresse du client");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Téléphone du client");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CNI du client");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Email du client");

        clt3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                clt3CaretUpdate(evt);
            }
        });

        clt6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                clt6CaretUpdate(evt);
            }
        });

        clb2.setText("Annuler");
        clb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clb2ActionPerformed(evt);
            }
        });

        clb1.setText("Enregistrer");
        clb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clt1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clt5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clt6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clb1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(clb2)
                                .addGap(47, 47, 47))
                            .addComponent(clt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(clt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(clt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clb1)
                    .addComponent(clb2))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clb2ActionPerformed
        reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_clb2ActionPerformed

    private void clt6FocusLost(java.awt.event.FocusEvent evt) {                               
        // TODO add your handling code here:
        if((this.clt6.getText().trim().length()>12)){
        JOptionPane.showMessageDialog(null,"La cni doit avoir 12 chiffres au maximum !!!");
        }else if((this.clt6.getText().trim().length()<10)){
        JOptionPane.showMessageDialog(null,"La cni doit avoir 10 chiffres au minimum !!!"); }
    }
    
    
    
    private void clb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clb1ActionPerformed

        String val;
        Client cl = new Client();
        cl.setNom(clt1.getText().trim());
        cl.setPrenom(clt2.getText().trim());
        cl.setAdresse(clt4.getText().trim());
        cl.setTel(clt3.getText().trim());
        cl.setEmail(clt5.getText().trim());
        cl.setNum_cni(clt6.getText().trim());

        boolean ver = verifierClient(cl);
        if (ver) {
            System.out.println("vue");
            if (DAOFactory.getClientDAO().create(cl)) {
                val = "Enregistrement éffectué !!";
                reset();
            } else {
                val = " Echec enregistrement !! \n Veuillez recommencer svp";
            }
            JOptionPane.showMessageDialog(null, val);


            // TODO add your handling code here:
    }//GEN-LAST:event_clb1ActionPerformed

        else {
            JOptionPane.showMessageDialog(null, "Verifiez que tous les champs sont remplis,\nque le no de Telephone etde CNI sont des\n chiffres uniquement  et que votre adresse email est correcte :monnom@site.domain !!! ");
        }
    }

    private void reset() {
        clt1.setText("");
        clt2.setText("");
        clt3.setText("");
        clt4.setText("");
        clt5.setText("");
        clt6.setText("");

    }

    private boolean verifierClient(Client clt) {
        int j = 0;
        
        if (!clt.getNom().isEmpty() && (!clt.getPrenom().isEmpty() && !clt.getNum_cni().isEmpty() && !clt.getTel().isEmpty() && !clt.getEmail().isEmpty())) {
            String model = "\\d{7,}";
            if (!Pattern.matches(model, clt.getTel())) {
                j += 1;
            }

            if (!Pattern.matches("\\d{10,}", clt.getNum_cni())) {
                j += 1;
            }
            int k = 0, i = 0;
            StringTokenizer em, emd;
            em = new StringTokenizer(clt.getEmail(), "@");
            emd = new StringTokenizer(clt.getEmail(), ".");
            while (em.hasMoreElements()) {
                System.out.println(em.nextElement());
                k++;
            }
             while (emd.hasMoreElements()) {
                System.out.println(emd.nextElement());
                i++;
            }

            if (k != 2 || i != 2 ) {
                j += 1;
            }

            if (j == 0) {
                test = true;
            } else {
                test = false;
            }


        } else {
            test = false;
        }
        
        return test;
    }
                                    // create instance
       public static CreateClients getInstance(){
    
    CreateClients cli=null; 
    
    if(!teste ){
        cli=new CreateClients();
        cli.setVisible(true);
        teste =true;
    }
    
    return cli;
}  
        
        private void clt3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_clt3CaretUpdate
 
    //permet de verifier les saisies des users
       String clt = clt3.getText();
        try{
            if(clt.length()>0){
        Integer.parseInt(clt3.getText());
        clb1.setEnabled(true);}
        }catch(NumberFormatException ex){
   JOptionPane.showMessageDialog(null, "veuillez saisir correctement le telephone", "Alerte telephonique", JOptionPane.WARNING_MESSAGE);
        //JOptionPane.showMessageDialog(null, "Le format saisi est incorrect");
        } 

            // TODO add your handling code here:
    }//GEN-LAST:event_clt3CaretUpdate

    private void clt6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_clt6CaretUpdate
//permet de verifier les saisies des users
       String cn = clt6.getText();
        try{
            if(cn.length()>0){
        Integer.parseInt(clt6.getText());
        clb1.setEnabled(true);}
        }catch(NumberFormatException ex){
   JOptionPane.showMessageDialog(null, "veuillez saisir correctement le numero de la cni", "Alerte numero cni", JOptionPane.WARNING_MESSAGE);
        //JOptionPane.showMessageDialog(null, "Le format saisi est incorrect");
        } 

        // TODO add your handling code here:
    }//GEN-LAST:event_clt6CaretUpdate

 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreateClients().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clb1;
    private javax.swing.JButton clb2;
    private javax.swing.JTextField clt1;
    private javax.swing.JTextField clt2;
    private javax.swing.JTextField clt3;
    private javax.swing.JTextField clt4;
    private javax.swing.JTextField clt5;
    private javax.swing.JTextField clt6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
