/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Dao.ObjetDao;
import Modele.Dao.PretDao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;

/**
 *
 * @author NANA
 */
public class MainView extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form MainView
     */
    
      PretDao prDao=new PretDao();
      ObjetDao obDao=new ObjetDao();
      private  int actionJtable;
     
      
            
    public MainView(String login) {
        initComponents();
        this.setLocationRelativeTo(null);
      
        String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.getListPret(),title));
       
        Toolkit kit=Toolkit.getDefaultToolkit();
        Dimension screenSize =kit.getScreenSize();
        int largeurEcran = screenSize.width;
        int hauteurEcran = screenSize.height;
        this.setSize(largeurEcran, hauteurEcran);
        
        this.bienvenue.setText("Bienvenue "+login); // message de bienvenue a
        this.titleTable.setText("Liste des Prets");
        
//        this.jLabel2.setIcon(new ImageIcon("banniereAppliSwing.PNG"));
        
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        enregB = new javax.swing.JButton();
        consulB = new javax.swing.JButton();
        modifB = new javax.swing.JButton();
        suppB = new javax.swing.JButton();
        quitB = new javax.swing.JButton();
        suppB1 = new javax.swing.JButton();
        bienvenue = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleTable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        quitM = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        modifCliM = new javax.swing.JMenuItem();
        modifObM = new javax.swing.JMenuItem();
        modifPretM = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        enregCliM = new javax.swing.JMenuItem();
        enregObM = new javax.swing.JMenuItem();
        enregPretM = new javax.swing.JMenuItem();
        configM = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        suppCliM = new javax.swing.JMenuItem();
        suppObM = new javax.swing.JMenuItem();
        alertes = new javax.swing.JMenuItem();
        restituerPrets = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des Prets");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        enregB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enregB.setForeground(new java.awt.Color(0, 153, 102));
        enregB.setText("Enregistrer un pret");
        enregB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregBActionPerformed(evt);
            }
        });

        consulB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        consulB.setForeground(new java.awt.Color(0, 153, 102));
        consulB.setText("Enregistrer un objet");
        consulB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consulB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulBActionPerformed(evt);
            }
        });

        modifB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modifB.setForeground(new java.awt.Color(0, 153, 102));
        modifB.setText("Consulter Pret");
        modifB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifBActionPerformed(evt);
            }
        });

        suppB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        suppB.setForeground(new java.awt.Color(0, 153, 102));
        suppB.setText("Consulter Objet");
        suppB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppBActionPerformed(evt);
            }
        });

        quitB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitB.setForeground(new java.awt.Color(0, 153, 102));
        quitB.setText("Déconnexion");
        quitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }
        });

        suppB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        suppB1.setForeground(new java.awt.Color(0, 153, 102));
        suppB1.setText("Consulter historisque");
        suppB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppB1ActionPerformed(evt);
            }
        });

        bienvenue.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        bienvenue.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppB, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(modifB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enregB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppB1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(bienvenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enregB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(consulB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(modifB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(suppB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(suppB1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));
        jPanel4.setForeground(new java.awt.Color(204, 255, 153));

        jLabel1.setText("@ Powery by WISE ONE Designed by Babarian group GL IUT 2013  All rights reserved");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        titleTable.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        titleTable.setForeground(new java.awt.Color(0, 153, 102));
        titleTable.setText("List");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(titleTable, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(titleTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vue/banniereAppliSwing.png"))); // NOI18N

        jMenu1.setText("Fichier");

        quitM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        quitM.setText("Quitter");
        quitM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMActionPerformed(evt);
            }
        });
        jMenu1.add(quitM);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editer");

        jMenu7.setText("Modifier");

        modifCliM.setText("Client");
        modifCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifCliM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifCliMActionPerformed(evt);
            }
        });
        jMenu7.add(modifCliM);

        modifObM.setText("Objet");
        modifObM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifObM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifObMActionPerformed(evt);
            }
        });
        jMenu7.add(modifObM);

        modifPretM.setText("Prêt");
        modifPretM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifPretM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifPretMActionPerformed(evt);
            }
        });
        jMenu7.add(modifPretM);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Options");

        jMenu8.setText("Enregistrer");

        enregCliM.setText("Client");
        enregCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregCliM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregCliMActionPerformed(evt);
            }
        });
        jMenu8.add(enregCliM);

        enregObM.setText("Objet");
        enregObM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregObM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregObMActionPerformed(evt);
            }
        });
        jMenu8.add(enregObM);

        enregPretM.setText("Prêt");
        enregPretM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enregPretM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregPretMActionPerformed(evt);
            }
        });
        jMenu8.add(enregPretM);

        jMenu5.add(jMenu8);

        configM.setText("Configurer");
        configM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.add(configM);

        jMenu9.setText("Supprimer");

        suppCliM.setText("Client");
        suppCliM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppCliM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppCliMActionPerformed(evt);
            }
        });
        jMenu9.add(suppCliM);

        suppObM.setText("Objet");
        suppObM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suppObM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppObMActionPerformed(evt);
            }
        });
        jMenu9.add(suppObM);

        jMenu5.add(jMenu9);

        alertes.setText("Consulter les Alertes");
        alertes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alertes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertesActionPerformed(evt);
            }
        });
        jMenu5.add(alertes);

        restituerPrets.setText("Restituer Prets");
        restituerPrets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restituerPrets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restituerPretsActionPerformed(evt);
            }
        });
        jMenu5.add(restituerPrets);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("?");

        jMenuItem11.setText("Aide");
        jMenuItem11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("A propos");
        jMenuItem12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Documentation");
        jMenu6.add(jMenuItem13);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifPretMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifPretMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifPretMActionPerformed

    private void quitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBActionPerformed
//this.dispose();
      //System.exit(0);
     int reponse =JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment quitter l'application ?", 
"Déconnexion", JOptionPane.YES_NO_OPTION);
if(reponse ==JOptionPane.YES_OPTION){
    
JOptionPane.showMessageDialog(null, "Merci et à la prochaine") ;
//System.out.println("Déconnexion = oui : Aurevoir");
System.exit(0);
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_quitBActionPerformed

    private void suppBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppBActionPerformed

        String[] title={"Identifiant","types","Description","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(obDao.getListObjet(),title));
         this.titleTable.setText("Liste des Objets");
        // TODO add your handling code here:
    }//GEN-LAST:event_suppBActionPerformed

    private void enregBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregBActionPerformed

        new Formulaire_pret().setVisible(true);
        this.actionJtable=1;
        // TODO add your handling code here:
    }//GEN-LAST:event_enregBActionPerformed

    private void consulBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulBActionPerformed

        new Formulaire_objet().setVisible(true);
        this.actionJtable=2;
        // TODO add your handling code here:
    }//GEN-LAST:event_consulBActionPerformed

    private void suppB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppB1ActionPerformed

        String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.gestHistoriques(),title));
         this.titleTable.setText("Historiques");
        // TODO add your handling code here:
    }//GEN-LAST:event_suppB1ActionPerformed

    private void modifBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifBActionPerformed

        String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.getListPret(),title));
         this.titleTable.setText("Liste des Prets");
        // TODO add your handling code here:
    }//GEN-LAST:event_modifBActionPerformed

    private void alertesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertesActionPerformed

        
        String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.getAlerte(),title));
         this.titleTable.setText("Liste des Prets arrivant à échéance");
        // TODO add your handling code here:
    }//GEN-LAST:event_alertesActionPerformed

    private void suppCliMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppCliMActionPerformed

        new Suppression(this,true,1).setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_suppCliMActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        System.out.println("fermeture de la fenetre 369");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        if(this.actionJtable==1){
        String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.getListPret(),title));
         this.titleTable.setText("Liste des Prets");
        }else if(this.actionJtable==2){
            
            String[] title={"Identifiant","types","Description","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(obDao.getListObjet(),title));
         this.titleTable.setText("Liste des Objets");
            
        }else if(this.actionJtable==3){
            
            String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.gestHistoriques(),title));
         this.titleTable.setText("Historiques");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void suppObMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppObMActionPerformed

        new Suppression(this,true,2).setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_suppObMActionPerformed

    private void restituerPretsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restituerPretsActionPerformed
        
        
        new RestitutionVue(this,true).setVisible(true);
        this.actionJtable=3;
        
        
    }//GEN-LAST:event_restituerPretsActionPerformed

    private void quitMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMActionPerformed
   int reponse =JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment quitter l'application ?", 
"Déconnexion", JOptionPane.YES_NO_OPTION);
if(reponse ==JOptionPane.YES_OPTION){
    
JOptionPane.showMessageDialog(null, "Merci et à la prochaine") ;
//System.out.println("Déconnexion = oui : Aurevoir");
System.exit(0);
}else if(reponse ==JOptionPane.NO_OPTION){
    
JOptionPane.showMessageDialog(null, "Continuez alors") ;
//System.out.println("Déconnexion = non : Connectez vous maintenant");
} 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_quitMActionPerformed

    private void modifCliMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifCliMActionPerformed
new ModifieClients().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifCliMActionPerformed

    private void modifObMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifObMActionPerformed
   new Modifie_objet().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_modifObMActionPerformed

    private void enregCliMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregCliMActionPerformed
new CreateClients().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_enregCliMActionPerformed

    private void enregObMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregObMActionPerformed
new Formulaire_objet().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_enregObMActionPerformed

    private void enregPretMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregPretMActionPerformed
new Formulaire_pret().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_enregPretMActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new MainView("Borice").setVisible(true);
//            }
//        });
//    }
    
//    public  void setTable(Object[][] data,String[] tit){
//        
//        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(data,tit));
//        
//    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alertes;
    private javax.swing.JLabel bienvenue;
    private javax.swing.JMenuItem configM;
    private javax.swing.JButton consulB;
    private javax.swing.JButton enregB;
    private javax.swing.JMenuItem enregCliM;
    private javax.swing.JMenuItem enregObM;
    private javax.swing.JMenuItem enregPretM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifB;
    private javax.swing.JMenuItem modifCliM;
    private javax.swing.JMenuItem modifObM;
    private javax.swing.JMenuItem modifPretM;
    private javax.swing.JButton quitB;
    private javax.swing.JMenuItem quitM;
    private javax.swing.JMenuItem restituerPrets;
    private javax.swing.JButton suppB;
    private javax.swing.JButton suppB1;
    private javax.swing.JMenuItem suppCliM;
    private javax.swing.JMenuItem suppObM;
    private javax.swing.JLabel titleTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        
        PretDao prDao=new PretDao();
        String[] title={"Identifiant","Nom du client","Description","date Pret","delai","Quantite"};
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(prDao.getListPret(),title));
        System.out.println("c'est bon");
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void windowClosed(WindowEvent e) {
        
        System.out.println("fermeture de la fenetre");
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        System.out.println("fermeture de la fenetre");
    }
}
