/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.Dao.ClientDao;
import Modele.Dao.ObjetDao;
import javax.swing.JOptionPane;

/**
 *
 * @author djoum
 */
public class Suppression extends javax.swing.JDialog {

    /**
     * Creates new form SupprimerClient
     */
    private int action;
    private  JOptionPane jop = new JOptionPane();
    
    public Suppression(java.awt.Frame parent, boolean modal,int action) {
        super(parent, modal);
        this.action=action;
        initComponents();
        this.setLocationRelativeTo(null);
        
        if(this.action==1){
            this.titre.setText("Suppression clients");
            this.label.setText("Selection du client :");
        }else if(this.action==2){
            this.label.setText("Selection de l'objet :");
            this.titre.setText("Suppression Objets");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combosupp = new javax.swing.JComboBox();
        titre = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        valider = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Suppression");

        String[] lesNomClient=new String[new ClientDao().getClientName().length-1];
        String[] lesNomObjet=new String[new ObjetDao().getObjetName().length-1];
        if(this.action==1){
            System.arraycopy( (new ClientDao().getClientName()), 0, lesNomClient, 0, lesNomClient.length);
            combosupp.setModel(new javax.swing.DefaultComboBoxModel(lesNomClient));
            System.out.println("client");
        }else if(this.action==2){
            System.out.println("objet");
            System.arraycopy( (new ObjetDao().getObjetName()), 0, lesNomObjet, 0, lesNomObjet.length);
            combosupp.setModel(new javax.swing.DefaultComboBoxModel(lesNomObjet));

        }

        titre.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(102, 102, 255));

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(valider)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(combosupp, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combosupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(jButton1))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed

        int id=0,k=0;
        
        String index=combosupp.getSelectedItem().toString();
        String message="",title="";
        
        if(this.action==1) {message="Voulez-vous vraiment supprimer ce client\n car sa suppression entraine la suppression\n de tous les prets qu'il a effectué !";title="Suppression d'un client";}
        else if (this.action==2){message="Voulez-vous vraiment supprimer cet objet\n car sa suppression entraine la suppression\n de tous les prets le contenant !"; title="Suppression d'un Objet";}
        
        int option = JOptionPane.showConfirmDialog(null, message, title,	JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                                if(option != JOptionPane.NO_OPTION && option !=JOptionPane.CANCEL_OPTION && option != JOptionPane.CLOSED_OPTION){
					
        for(int i=0;i<index.length();i++){
                
                if(index.charAt(i)=='-'){
                  id=Integer.parseInt(index.substring(k, i));  
                  
                  break;
                }
            }
        if(this.action==1){
            
        ClientDao clidao= new ClientDao();
   clidao.delete(clidao.getClientById(id));
   
        }else if(this.action==2){
            
            ObjetDao obdao=new ObjetDao();
            obdao.delete(obdao.getObjetById(id));
           
        }
        
        this.dispose();
        
      }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_validerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Suppression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                Suppression dialog = new Suppression(new javax.swing.JFrame(), true,2);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combosupp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel titre;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
